server:
  port: 9080
  
spring:
 application:
  name: hr-service
  
 eureka:
  client:
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/
          
      
    
     